name: project CI flow

on:
  push:
    branches: [ develop ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - name: Build with Maven
        run: |
          mvn clean test install
          cd ${{ github.workspace }}/target/site/jacoco
          ls -la

      - name: Jacoco Report
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 10
          min-coverage-changed-files: 10
          title: 'Coverage Report'
          update-comment: true
          debug-mode: false

      - uses: actions/upload-artifact@v3
        with:
          name: report coverage
          path: ${{ github.workspace }}/target/site/jacoco
            
      - name: Get the Coverage info
        run: |
          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"

      - name: Fail if overall coverage is less than 10%
        if: ${{ steps.jacoco.outputs.coverage-overall < 60.0 }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Overall coverage is less than 10%!')

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build . --tag ghcr.io/juanfgr/akkodis-exercise:latest
          docker run -p 8080:8080 -d ghcr.io/juanfgr/akkodis-exercise:latest
          docker push ghcr.io/juanfgr/akkodis-exercise:latest